#! /bin/bash
# enconding: utf-8

cd "$(dirname $0)"
PROJECT_ROOT=$(cd ..; pwd)

get_app_version() {
    sed -n '/CFBundleVersion/{n;s/.*<string>\(.*\)<\/string>.*/\1/;p;}' $@
}

appcast_file='appcast.xml'
app_version=$(get_app_version "${PROJECT_ROOT}/Info.plist")
download_url="http://dl.bintray.com/lotem/rime/Squirrel-${app_version}.zip"
target_archive="archives/Squirrel-${app_version}.zip"

if [ -n "${testing}" ]; then
    appcast_file='test-appcast.xml'
    download_url="${PROJECT_ROOT}/package/${target_archive}"
    target_archive='test-archive.zip'
    rm -f "${target_archive}" > /dev/null 2>&1 || true
fi

if [ -e "${target_archive}" ]; then
  echo "ERROR: target archive already exists: ${target_archive}"
  exit 1
fi

zip -r "${target_archive}" Squirrel.pkg

dsa_signature=$(ruby sign/sign_update.rb "${target_archive}" sign/dsa_priv.pem)
file_length=$(stat -f%z "${target_archive}")
pub_date=$(date -R)

cat > "${appcast_file}" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
  <channel>
    <title>【鼠鬚管】輸入法更新頻道</title>
    <link>http://rime.github.io/release/squirrel/appcast.xml</link>
    <description>鼠鬚管 Appcast 更新頻道</description>
    <language>zh</language>
    <item>
      <title>鼠鬚管 ${app_version}</title>
      <sparkle:releaseNotesLink>http://rime.github.io/release/squirrel/</sparkle:releaseNotesLink>
      <sparkle:minimumSystemVersion>10.7.0</sparkle:minimumSystemVersion>
      <pubDate>${pub_date}</pubDate>
      <enclosure url="${download_url}"
                 sparkle:version="${app_version}"
                 sparkle:dsaSignature="${dsa_signature}"
                 length="${file_length}"
                 type="application/octet-stream"/>
    </item>
  </channel>
</rss>
EOF

ls -l ${appcast_file} ${target_archive}
