#!/bin/bash

DERIVED_DATA_PATH=$1
BUNDLE_IDENTIFIER='im.rime.inputmethod.Squirrel'
INSTALL_LOCATION='/Library/Input Methods'

cd "$(dirname $0)"
source common.sh

if [ -e "${PROJECT_ROOT}/build/Squirrel.app" ]; then
    ROOT=`mktemp -d`
    cp -a "${PROJECT_ROOT}/build/Squirrel.app" "$ROOT"
else
    ROOT="${PROJECT_ROOT}/${DERIVED_DATA_PATH}/Build/Products/Release"
fi

pkgbuild \
    --info PackageInfo \
    --root "$ROOT" \
    --filter '.*\.swiftmodule$' \
    --component-plist Squirrel-component.plist \
    --identifier "${BUNDLE_IDENTIFIER}" \
    --version "$(get_app_version)" \
    --install-location "${INSTALL_LOCATION}" \
    --scripts "${PROJECT_ROOT}/scripts" \
    Squirrel.pkg
