#! /bin/bash
# enconding: utf-8

cd "$(dirname $0)"
PROJECT_ROOT="$(cd ..; pwd)"

get_app_version() {
    sed -n '/CFBundleVersion/{n;s/.*<string>\(.*\)<\/string>.*/\1/;p;}' $@
}

app_version=$(get_app_version "${PROJECT_ROOT}/Info.plist")
download_url="https://dl.bintray.com/rime/squirrel/Squirrel-${app_version}.zip"
target_archive="archives/Squirrel-${app_version}.zip"

if [ -n "${checksum}" ]; then
    if ! [ -f "${target_archive}" ]; then
        echo >&2 "ERROR: file does not exit: ${target_archive}"
        exit 1
    fi
    echo 'sha256 checksum:'
    echo "${checksum}  ${target_archive}"
    shasum -a 256 -c <<<"${checksum}  ${target_archive}" || exit 1
else
    if [ -e "${target_archive}" ]; then
        echo >&2 "ERROR: target archive already exists: ${target_archive}"
        exit 1
    fi
    zip -r "${target_archive}" Squirrel.pkg
    echo 'sha256 checksum:'
    shasum -a 256 "${target_archive}"
fi

ls -l ${target_archive}

dsa_signature=$(ruby sign/sign_update.rb "${target_archive}" sign/dsa_priv.pem)
file_length=$(stat -f%z "${target_archive}")
pub_date=$(date -R)

# for release channel
appcast_file='appcast.xml'

cat > "${appcast_file}" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
  <channel>
    <title>【鼠鬚管】輸入法更新頻道</title>
    <link>https://rime.github.io/release/squirrel/appcast.xml</link>
    <description>鼠鬚管 Appcast 更新頻道</description>
    <language>zh</language>
    <item>
      <title>鼠鬚管 ${app_version}</title>
      <sparkle:releaseNotesLink>https://rime.github.io/release/squirrel/</sparkle:releaseNotesLink>
      <sparkle:minimumSystemVersion>10.7.0</sparkle:minimumSystemVersion>
      <pubDate>${pub_date}</pubDate>
      <enclosure url="${download_url}"
                 sparkle:version="${app_version}"
                 sparkle:dsaSignature="${dsa_signature}"
                 length="${file_length}"
                 type="application/octet-stream"/>
    </item>
  </channel>
</rss>
EOF

ls -l ${appcast_file}

# for testing channel
appcast_file='testing-appcast.xml'

cat > "${appcast_file}" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
  <channel>
    <title>【鼠鬚管】輸入法測試頻道</title>
    <link>https://rime.github.io/testing/squirrel/appcast.xml</link>
    <description>鼠鬚管測試版 Appcast 更新頻道</description>
    <language>zh</language>
    <item>
      <title>鼠鬚管 ${app_version}</title>
      <sparkle:releaseNotesLink>https://rime.github.io/testing/squirrel/</sparkle:releaseNotesLink>
      <sparkle:minimumSystemVersion>10.7.0</sparkle:minimumSystemVersion>
      <pubDate>${pub_date}</pubDate>
      <enclosure url="${download_url}"
                 sparkle:version="${app_version}"
                 sparkle:dsaSignature="${dsa_signature}"
                 length="${file_length}"
                 type="application/octet-stream"/>
    </item>
  </channel>
</rss>
EOF

ls -l ${appcast_file}

# for testing appcast push locally.
appcast_file='debug-appcast.xml'
download_url="${PROJECT_ROOT}/package/${target_archive}"

cat > "${appcast_file}" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
  <channel>
    <title>【鼠鬚管】輸入法本地測試</title>
    <link>file://${PROJECT_ROOT}/package/${appcast_file}</link>
    <description>鼠鬚管 Appcast 更新本地測試</description>
    <language>zh</language>
    <item>
      <title>鼠鬚管 ${app_version}</title>
      <sparkle:releaseNotesLink>https://rime.github.io/testing/squirrel/</sparkle:releaseNotesLink>
      <sparkle:minimumSystemVersion>10.7.0</sparkle:minimumSystemVersion>
      <pubDate>${pub_date}</pubDate>
      <enclosure url="${download_url}"
                 sparkle:version="${app_version}"
                 sparkle:dsaSignature="${dsa_signature}"
                 length="${file_length}"
                 type="application/octet-stream"/>
    </item>
  </channel>
</rss>
EOF

ls -l ${appcast_file}
