#! /bin/bash

version=$1
target=archives/Squirrel-${version}.zip

if [ -z "$version" ]; then
  echo "missing argument: version"
  exit 1
fi

if [ -e "${target}" ]; then
  echo "target file ${target} already exists !"
  exit 1
fi

zip -r ${target} Squirrel.pkg

ruby sign/sign_update.rb ${target} sign/dsa_priv.pem >> ../update/appcast.xml
ls -l ${target} >> ../update/appcast.xml
vim ../update/appcast.xml
