#! /bin/bash
# enconding: utf-8

DEV_ID=$1
DERIVED_DATA_PATH=$2
appDir="${DERIVED_DATA_PATH}/Build/Products/Release/SquirrelFlypy.app"
entitlement="resources/SquirrelFlypy.entitlements"

codesign --deep --force --options runtime --timestamp --sign "Developer ID Application: ${DEV_ID}" --entitlements "$entitlement" --verbose "$appDir";

spctl -a -vv "$appDir";
