name: pull request ci
on: [pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Squirrel
        run: ./action-build.sh

      - name: Upload Squirrel artifact
        uses: actions/upload-artifact@v3
        with:
          name: squirrel.zip
          path: ./**/*.pkg
          # keep 30 days
          retention-days: 30
